channels:
- conda-forge
dependencies:
- python=3.12.3
- pip<=25.3
- pip:
  - mlflow==3.5.1
  - cloudpickle==3.1.1
  - numpy==2.3.4
  - psutil==7.1.2
  - scikit-learn==1.4.2
  - scipy==1.16.2
name: mlflow-env
